// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uehvxrmptkdptymcfzpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlaHZ4cm1wdGtkcHR5bWNmenB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzODI2NjEsImV4cCI6MjA1MDk1ODY2MX0.yu3VqeshS72YPf54FlD1XKuLAjKn_aXmiRPKzNhphqk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);